# this makefile also gets parsed by shell scripts
# therefore it does not support full make syntax and features
# edit with care

PACKAGE          = DileptonMatrixMethod
PACKAGE_PRELOAD  = 
PACKAGE_CXXFLAGS = 
PACKAGE_OBJFLAGS = 
PACKAGE_LDFLAGS  = $(shell root-config --libs --glibs)
PACKAGE_BINFLAGS = -lPyROOT -lXMLParser -lEG
PACKAGE_DEP      = 
PACKAGE_TRYDEP   = 
PACKAGE_CLEAN    = 
PACKAGE_NOOPT    = 0
PACKAGE_NOCC     = 0

include $(ROOTCOREDIR)/Makefile-common
